/*
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * Copyright 2022, Wabi Animation Studios, Ltd. Co.
 */

#ifndef KRAKEN_WABI_PYTHON_H
#define KRAKEN_WABI_PYTHON_H

#include <Python.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * These seemingly magical functions
 * are autogenerated from Pixar USD's
 * TF_WRAP_MODULE() functions, here;
 * we just declare them so that we
 * can call them manually...
 */

PyObject *PyInit__tf(void);
PyObject *PyInit__gf(void);
PyObject *PyInit__trace(void);
PyObject *PyInit__work(void);
PyObject *PyInit__plug(void);
PyObject *PyInit__vt(void);
PyObject *PyInit__ar(void);
PyObject *PyInit__kind(void);
PyObject *PyInit__sdf(void);
PyObject *PyInit__ndr(void);
PyObject *PyInit__sdr(void);
PyObject *PyInit__pcp(void);
PyObject *PyInit__usd(void);
PyObject *PyInit__usdGeom(void);
PyObject *PyInit__usdVol(void);
PyObject *PyInit__usdMedia(void);
PyObject *PyInit__usdShade(void);
PyObject *PyInit__usdLux(void);
PyObject *PyInit__usdRender(void);
PyObject *PyInit__usdHydra(void);
PyObject *PyInit__usdRi(void);
PyObject *PyInit__usdSkel(void);
PyObject *PyInit__usdUI(void);
PyObject *PyInit__usdUtils(void);
PyObject *PyInit__usdPhysics(void);
PyObject *PyInit__usdAbc(void);
PyObject *PyInit__usdDraco(void);
PyObject *PyInit__garch(void);
PyObject *PyInit__cameraUtil(void);
PyObject *PyInit__pxOsd(void);
PyObject *PyInit__glf(void);
PyObject *PyInit__usdImagingGL(void);
PyObject *PyInit__usdAppUtils(void);
PyObject *PyInit__usdviewq(void);

PyObject *PyInit_libtf(void);
PyObject *PyInit_libgf(void);
PyObject *PyInit_libtrace(void);
PyObject *PyInit_libwork(void);
PyObject *PyInit_libplug(void);
PyObject *PyInit_libvt(void);
PyObject *PyInit_libar(void);
PyObject *PyInit_libkind(void);
PyObject *PyInit_libsdf(void);
PyObject *PyInit_libndr(void);
PyObject *PyInit_libsdr(void);
PyObject *PyInit_libpcp(void);
PyObject *PyInit_libusd(void);
PyObject *PyInit_libusdGeom(void);
PyObject *PyInit_libusdVol(void);
PyObject *PyInit_libusdMedia(void);
PyObject *PyInit_libusdShade(void);
PyObject *PyInit_libusdLux(void);
PyObject *PyInit_libusdRender(void);
PyObject *PyInit_libusdHydra(void);
PyObject *PyInit_libusdRi(void);
PyObject *PyInit_libusdSkel(void);
PyObject *PyInit_libusdUI(void);
PyObject *PyInit_libusdUtils(void);
PyObject *PyInit_libusdPhysics(void);
PyObject *PyInit_libusdAbc(void);
PyObject *PyInit_libusdDraco(void);
PyObject *PyInit_libgarch(void);
PyObject *PyInit_libcameraUtil(void);
PyObject *PyInit_libpxOsd(void);
PyObject *PyInit_libglf(void);
PyObject *PyInit_libusdImagingGL(void);
PyObject *PyInit_libusdAppUtils(void);
PyObject *PyInit_libusdviewq(void);

#ifdef __cplusplus
}
#endif

#endif /* KRAKEN_WABI_PYTHON_H */