// Copyright © 2021 Wabi Animation Studios. All rights reserved.

namespace kraken
{
  [default_interface]
  runtimeclass MainWindow : Microsoft.UI.Xaml.Window
  {
    MainWindow();

    Microsoft.UI.Windowing.AppWindow AppWindow { get; };
    Microsoft.UI.Xaml.Controls.Grid TitleBar{ get; };
    Microsoft.UI.Xaml.Controls.Image WindowIcon{ get; };
  };
}
