# 
#  Copyright 2021 Pixar. All Rights Reserved.
# 
#  Portions of this file are derived from original work by Pixar
#  distributed with Universal Scene Description, a project of the
#  Academy Software Foundation (ASWF). https://www.aswf.io/
# 
#  Licensed under the Apache License, Version 2.0 (the "Apache License")
#  with the following modification; you may not use this file except in
#  compliance with the Apache License and the following modification:
#  Section 6. Trademarks. is deleted and replaced with:
# 
#  6. Trademarks. This License does not grant permission to use the trade
#     names, trademarks, service marks, or product names of the Licensor
#     and its affiliates, except as required to comply with Section 4(c)
#     of the License and to reproduce the content of the NOTICE file.
#
#  You may obtain a copy of the Apache License at:
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the Apache License with the above modification is
#  distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF
#  ANY KIND, either express or implied. See the Apache License for the
#  specific language governing permissions and limitations under the
#  Apache License.
#
#  Modifications copyright (C) 2020-2021 Wabi.
#
def GetPySideModule():
    """Returns name of PySide module used by usdview,
    e.g. 'PySide' or 'PySide2'"""
    # Inspect objects imported in a UI module generated by uic to determine
    # which PySide module they come from (e.g. PySide.QtCore, PySide2.QtCore).
    # This insulates the code from assuming that the generated code will
    # import something specific.
    from . import attributeValueEditorUI
    import inspect

    for name in dir(attributeValueEditorUI):
        obj = getattr(attributeValueEditorUI, name)
        module = inspect.getmodule(obj)
        if module and module.__name__.startswith('PySide'):
            return module.__name__.split('.')[0]

    return None

PySideModule = GetPySideModule()
if PySideModule == 'PySide':
    from PySide import QtCore, QtGui, QtOpenGL
    from PySide import QtGui as QtWidgets

    # Patch missing functions to make PySide look like PySide2
    if not hasattr(QtGui.QApplication, 'devicePixelRatio'):
        QtGui.QApplication.devicePixelRatio = lambda self: 1

    if not hasattr(QtOpenGL.QGLWidget, 'devicePixelRatioF'):
        QtOpenGL.QGLWidget.devicePixelRatioF = lambda self: 1.0

    if not hasattr(QtWidgets.QHeaderView, 'setSectionResizeMode'):
        QtWidgets.QHeaderView.setSectionResizeMode = \
            QtWidgets.QHeaderView.setResizeMode

    if not hasattr(QtGui.QMenu, 'setToolTipsVisible'):
        QtGui.QMenu.setToolTipsVisible = lambda self, _: None

    if hasattr(QtGui.QWheelEvent, 'pixelDelta') \
        and not hasattr(QtGui.QWheelEvent, 'angleDelta'):
        def angleDelta(self):
            return self.pixelDelta()
        QtGui.QWheelEvent.angleDelta = angleDelta

    # Patch missing classes to make PySide look like PySide2
    if not hasattr(QtCore, 'QItemSelectionModel'):
        QtCore.QItemSelectionModel = QtGui.QItemSelectionModel

    if not hasattr(QtCore, 'QStringListModel'):
        QtCore.QStringListModel = QtGui.QStringListModel

elif PySideModule == 'PySide2':
    from PySide2 import QtCore, QtGui, QtWidgets, QtOpenGL

    # Older versions still have QtGui.QStringListModel - this
    # is apparently a bug:
    #    https://bugreports.qt.io/browse/PYSIDE-614
    if not hasattr(QtCore, 'QStringListModel'):
        QtCore.QStringListModel = QtGui.QStringListModel
else:
    raise ImportError('Unrecognized PySide module "{}"'.format(PySideModule))
