/*
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * Copyright 2022, Wabi Animation Studios, Ltd. Co.
 */

/**
 * @file
 * Window Manager.
 * Making GUI Fly.
 */

#pragma once

#include "WM_api.h"

#include "USD_api.h"

#include <wabi/base/tf/token.h>

KRAKEN_NAMESPACE_BEGIN

struct KRAKEN_WM_TOKENS_TYPE
{
  KRAKEN_WM_TOKENS_TYPE();

  /* ----------------------------------- files ops ----- */
  KRAKEN_DECLARE_STATIC_TOKEN(WM_OT_files_create_appdata);
  KRAKEN_DECLARE_STATIC_TOKEN(WM_OT_open_mainfile);
  KRAKEN_DECLARE_STATIC_TOKEN(WM_OT_save_mainfile);

  /* -------------------------------------- ui ops ----- */
  KRAKEN_DECLARE_STATIC_TOKEN(WM_OT_call_menu);
  KRAKEN_DECLARE_STATIC_TOKEN(WM_OT_call_panel);
  KRAKEN_DECLARE_STATIC_TOKEN(WM_OT_context_toggle);
  KRAKEN_DECLARE_STATIC_TOKEN(WM_OT_context_toggle_enum);
  KRAKEN_DECLARE_STATIC_TOKEN(WM_OT_context_cycle_int);
  KRAKEN_DECLARE_STATIC_TOKEN(WM_OT_context_cycle_enum);
  KRAKEN_DECLARE_STATIC_TOKEN(WM_OT_context_cycle_array);
  KRAKEN_DECLARE_STATIC_TOKEN(WM_OT_context_menu_enum);
  KRAKEN_DECLARE_STATIC_TOKEN(WM_OT_context_set_enum);
  KRAKEN_DECLARE_STATIC_TOKEN(SCREEN_OT_space_type_set_or_cycle);

  /* --------------------------------- windows ops ----- */
  KRAKEN_DECLARE_STATIC_TOKEN(WM_OT_window_close);
  KRAKEN_DECLARE_STATIC_TOKEN(WM_OT_window_new);
  KRAKEN_DECLARE_STATIC_TOKEN(WM_OT_window_new_main);
  KRAKEN_DECLARE_STATIC_TOKEN(WM_OT_window_fullscreen_toggle);
  KRAKEN_DECLARE_STATIC_TOKEN(WM_OT_quit_kraken);

  /* ---------------------------- event type enums ----- */
  KRAKEN_DECLARE_STATIC_TOKEN(NONE);
  KRAKEN_DECLARE_STATIC_TOKEN(LEFTMOUSE);
  KRAKEN_DECLARE_STATIC_TOKEN(MIDDLEMOUSE);
  KRAKEN_DECLARE_STATIC_TOKEN(RIGHTMOUSE);
  KRAKEN_DECLARE_STATIC_TOKEN(BUTTON4MOUSE);
  KRAKEN_DECLARE_STATIC_TOKEN(BUTTON5MOUSE);
  KRAKEN_DECLARE_STATIC_TOKEN(BUTTON6MOUSE);
  KRAKEN_DECLARE_STATIC_TOKEN(BUTTON7MOUSE);
  KRAKEN_DECLARE_STATIC_TOKEN(PEN);
  KRAKEN_DECLARE_STATIC_TOKEN(ERASER);
  KRAKEN_DECLARE_STATIC_TOKEN(MOUSEMOVE);
  KRAKEN_DECLARE_STATIC_TOKEN(INBETWEEN_MOUSEMOVE);
  KRAKEN_DECLARE_STATIC_TOKEN(TRACKPADPAN);
  KRAKEN_DECLARE_STATIC_TOKEN(TRACKPADZOOM);
  KRAKEN_DECLARE_STATIC_TOKEN(MOUSEROTATE);
  KRAKEN_DECLARE_STATIC_TOKEN(MOUSESMARTZOOM);
  KRAKEN_DECLARE_STATIC_TOKEN(WHEELUPMOUSE);
  KRAKEN_DECLARE_STATIC_TOKEN(WHEELDOWNMOUSE);
  KRAKEN_DECLARE_STATIC_TOKEN(WHEELINMOUSE);
  KRAKEN_DECLARE_STATIC_TOKEN(WHEELOUTMOUSE);
  KRAKEN_DECLARE_STATIC_TOKEN(A);
  KRAKEN_DECLARE_STATIC_TOKEN(B);
  KRAKEN_DECLARE_STATIC_TOKEN(C);
  KRAKEN_DECLARE_STATIC_TOKEN(D);
  KRAKEN_DECLARE_STATIC_TOKEN(E);
  KRAKEN_DECLARE_STATIC_TOKEN(F);
  KRAKEN_DECLARE_STATIC_TOKEN(G);
  KRAKEN_DECLARE_STATIC_TOKEN(H);
  KRAKEN_DECLARE_STATIC_TOKEN(I);
  KRAKEN_DECLARE_STATIC_TOKEN(J);
  KRAKEN_DECLARE_STATIC_TOKEN(K);
  KRAKEN_DECLARE_STATIC_TOKEN(L);
  KRAKEN_DECLARE_STATIC_TOKEN(M);
  KRAKEN_DECLARE_STATIC_TOKEN(N);
  KRAKEN_DECLARE_STATIC_TOKEN(O);
  KRAKEN_DECLARE_STATIC_TOKEN(P);
  KRAKEN_DECLARE_STATIC_TOKEN(Q);
  KRAKEN_DECLARE_STATIC_TOKEN(R);
  KRAKEN_DECLARE_STATIC_TOKEN(S);
  KRAKEN_DECLARE_STATIC_TOKEN(T);
  KRAKEN_DECLARE_STATIC_TOKEN(U);
  KRAKEN_DECLARE_STATIC_TOKEN(V);
  KRAKEN_DECLARE_STATIC_TOKEN(W);
  KRAKEN_DECLARE_STATIC_TOKEN(X);
  KRAKEN_DECLARE_STATIC_TOKEN(Y);
  KRAKEN_DECLARE_STATIC_TOKEN(Z);
  KRAKEN_DECLARE_STATIC_TOKEN(ZERO);
  KRAKEN_DECLARE_STATIC_TOKEN(ONE);
  KRAKEN_DECLARE_STATIC_TOKEN(TWO);
  KRAKEN_DECLARE_STATIC_TOKEN(THREE);
  KRAKEN_DECLARE_STATIC_TOKEN(FOUR);
  KRAKEN_DECLARE_STATIC_TOKEN(FIVE);
  KRAKEN_DECLARE_STATIC_TOKEN(SIX);
  KRAKEN_DECLARE_STATIC_TOKEN(SEVEN);
  KRAKEN_DECLARE_STATIC_TOKEN(EIGHT);
  KRAKEN_DECLARE_STATIC_TOKEN(NINE);
  KRAKEN_DECLARE_STATIC_TOKEN(LEFT_CTRL);
  KRAKEN_DECLARE_STATIC_TOKEN(LEFT_ALT);
  KRAKEN_DECLARE_STATIC_TOKEN(LEFT_SHIFT);
  KRAKEN_DECLARE_STATIC_TOKEN(RIGHT_ALT);
  KRAKEN_DECLARE_STATIC_TOKEN(RIGHT_CTRL);
  KRAKEN_DECLARE_STATIC_TOKEN(RIGHT_SHIFT);
  KRAKEN_DECLARE_STATIC_TOKEN(OSKEY);
  KRAKEN_DECLARE_STATIC_TOKEN(APP);
  KRAKEN_DECLARE_STATIC_TOKEN(GRLESS);
  KRAKEN_DECLARE_STATIC_TOKEN(ESC);
  KRAKEN_DECLARE_STATIC_TOKEN(TAB);
  KRAKEN_DECLARE_STATIC_TOKEN(RET);
  KRAKEN_DECLARE_STATIC_TOKEN(SPACE);
  KRAKEN_DECLARE_STATIC_TOKEN(LINE_FEED);
  KRAKEN_DECLARE_STATIC_TOKEN(BACK_SPACE);
  KRAKEN_DECLARE_STATIC_TOKEN(DEL);
  KRAKEN_DECLARE_STATIC_TOKEN(SEMI_COLON);
  KRAKEN_DECLARE_STATIC_TOKEN(PERIOD);
  KRAKEN_DECLARE_STATIC_TOKEN(COMMA);
  KRAKEN_DECLARE_STATIC_TOKEN(QUOTE);
  KRAKEN_DECLARE_STATIC_TOKEN(ACCENT_GRAVE);
  KRAKEN_DECLARE_STATIC_TOKEN(MINUS);
  KRAKEN_DECLARE_STATIC_TOKEN(PLUS);
  KRAKEN_DECLARE_STATIC_TOKEN(SLASH);
  KRAKEN_DECLARE_STATIC_TOKEN(BACK_SLASH);
  KRAKEN_DECLARE_STATIC_TOKEN(EQUAL);
  KRAKEN_DECLARE_STATIC_TOKEN(LEFT_BRACKET);
  KRAKEN_DECLARE_STATIC_TOKEN(RIGHT_BRACKET);
  KRAKEN_DECLARE_STATIC_TOKEN(LEFT_ARROW);
  KRAKEN_DECLARE_STATIC_TOKEN(DOWN_ARROW);
  KRAKEN_DECLARE_STATIC_TOKEN(RIGHT_ARROW);
  KRAKEN_DECLARE_STATIC_TOKEN(UP_ARROW);
  KRAKEN_DECLARE_STATIC_TOKEN(NUMPAD_2);
  KRAKEN_DECLARE_STATIC_TOKEN(NUMPAD_4);
  KRAKEN_DECLARE_STATIC_TOKEN(NUMPAD_6);
  KRAKEN_DECLARE_STATIC_TOKEN(NUMPAD_8);
  KRAKEN_DECLARE_STATIC_TOKEN(NUMPAD_1);
  KRAKEN_DECLARE_STATIC_TOKEN(NUMPAD_3);
  KRAKEN_DECLARE_STATIC_TOKEN(NUMPAD_5);
  KRAKEN_DECLARE_STATIC_TOKEN(NUMPAD_7);
  KRAKEN_DECLARE_STATIC_TOKEN(NUMPAD_9);
  KRAKEN_DECLARE_STATIC_TOKEN(NUMPAD_PERIOD);
  KRAKEN_DECLARE_STATIC_TOKEN(NUMPAD_SLASH);
  KRAKEN_DECLARE_STATIC_TOKEN(UMPAD_ASTERIX);
  KRAKEN_DECLARE_STATIC_TOKEN(NUMPAD_0);
  KRAKEN_DECLARE_STATIC_TOKEN(NUMPAD_MINUS);
  KRAKEN_DECLARE_STATIC_TOKEN(NUMPAD_ENTER);
  KRAKEN_DECLARE_STATIC_TOKEN(NUMPAD_PLUS);
  KRAKEN_DECLARE_STATIC_TOKEN(F1);
  KRAKEN_DECLARE_STATIC_TOKEN(F2);
  KRAKEN_DECLARE_STATIC_TOKEN(F3);
  KRAKEN_DECLARE_STATIC_TOKEN(F4);
  KRAKEN_DECLARE_STATIC_TOKEN(F5);
  KRAKEN_DECLARE_STATIC_TOKEN(F6);
  KRAKEN_DECLARE_STATIC_TOKEN(F7);
  KRAKEN_DECLARE_STATIC_TOKEN(F8);
  KRAKEN_DECLARE_STATIC_TOKEN(F9);
  KRAKEN_DECLARE_STATIC_TOKEN(F10);
  KRAKEN_DECLARE_STATIC_TOKEN(F11);
  KRAKEN_DECLARE_STATIC_TOKEN(F12);
  KRAKEN_DECLARE_STATIC_TOKEN(F13);
  KRAKEN_DECLARE_STATIC_TOKEN(F14);
  KRAKEN_DECLARE_STATIC_TOKEN(F15);
  KRAKEN_DECLARE_STATIC_TOKEN(F16);
  KRAKEN_DECLARE_STATIC_TOKEN(F17);
  KRAKEN_DECLARE_STATIC_TOKEN(F18);
  KRAKEN_DECLARE_STATIC_TOKEN(F19);
  KRAKEN_DECLARE_STATIC_TOKEN(F20);
  KRAKEN_DECLARE_STATIC_TOKEN(F21);
  KRAKEN_DECLARE_STATIC_TOKEN(F22);
  KRAKEN_DECLARE_STATIC_TOKEN(F23);
  KRAKEN_DECLARE_STATIC_TOKEN(F24);
  KRAKEN_DECLARE_STATIC_TOKEN(PAUSE);
  KRAKEN_DECLARE_STATIC_TOKEN(INSERT);
  KRAKEN_DECLARE_STATIC_TOKEN(HOME);
  KRAKEN_DECLARE_STATIC_TOKEN(PAGE_UP);
  KRAKEN_DECLARE_STATIC_TOKEN(PAGE_DOWN);
  KRAKEN_DECLARE_STATIC_TOKEN(END);
  KRAKEN_DECLARE_STATIC_TOKEN(MEDIA_PLAY);
  KRAKEN_DECLARE_STATIC_TOKEN(MEDIA_STOP);
  KRAKEN_DECLARE_STATIC_TOKEN(MEDIA_FIRST);
  KRAKEN_DECLARE_STATIC_TOKEN(MEDIA_LAST);
  KRAKEN_DECLARE_STATIC_TOKEN(TEXTINPUT);
  KRAKEN_DECLARE_STATIC_TOKEN(WINDOW_DEACTIVATE);
  KRAKEN_DECLARE_STATIC_TOKEN(TIMER);
  KRAKEN_DECLARE_STATIC_TOKEN(TIMER0);
  KRAKEN_DECLARE_STATIC_TOKEN(TIMER1);
  KRAKEN_DECLARE_STATIC_TOKEN(TIMER2);
  KRAKEN_DECLARE_STATIC_TOKEN(TIMER_JOBS);
  KRAKEN_DECLARE_STATIC_TOKEN(TIMER_AUTOSAVE);
  KRAKEN_DECLARE_STATIC_TOKEN(TIMER_REPORT);
  KRAKEN_DECLARE_STATIC_TOKEN(TIMERREGION);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_MOTION);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_MENU);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_FIT);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_TOP);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_BOTTOM);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_LEFT);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_RIGHT);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_FRONT);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_BACK);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_ISO1);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_ISO2);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_ROLL_CW);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_ROLL_CCW);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_SPIN_CW);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_SPIN_CCW);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_TILT_CW);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_TILT_CCW);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_ROTATE);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_PANZOOM);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_DOMINANT);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_PLUS);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_MINUS);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_1);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_2);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_3);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_4);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_5);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_6);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_7);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_8);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_9);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_10);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_A);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_B);
  KRAKEN_DECLARE_STATIC_TOKEN(NDOF_BUTTON_C);
  KRAKEN_DECLARE_STATIC_TOKEN(ACTIONZONE_AREA);
  KRAKEN_DECLARE_STATIC_TOKEN(ACTIONZONE_REGION);
  KRAKEN_DECLARE_STATIC_TOKEN(ACTIONZONE_FULLSCREEN);
  KRAKEN_DECLARE_STATIC_TOKEN(XR_ACTION);

  const std::vector<TfToken> allTokens;
};

extern TfStaticData<KRAKEN_WM_TOKENS_TYPE> KRAKEN_WM_TOKENS;

KRAKEN_NAMESPACE_END