function(_add_define definition)
    set(_WABI_CXX_DEFINITIONS "${_WABI_CXX_DEFINITIONS} -D${definition}" PARENT_SCOPE)
endfunction()

function(_disable_warning flag)
    if(MSVC)
        set(_WABI_CXX_WARNING_FLAGS "${_WABI_CXX_WARNING_FLAGS} /wd${flag}" PARENT_SCOPE)
    else()
        set(_WABI_CXX_WARNING_FLAGS "${_WABI_CXX_WARNING_FLAGS} -Wno-${flag}" PARENT_SCOPE)
    endif()
endfunction()