// Copyright © 2021 Wabi Animation Studios. All rights reserved.

namespace Kraken
{
  namespace UIKit
  {
    delegate void SignalDelegate();


    [default_interface]
    runtimeclass UIEvent
    {
      UIEvent();

      Single TitleBar{ get; };
      Single NavigationView{ get; };
      Single Window{ get; };
    };

    
    [default_interface]
    runtimeclass UIResponder
    {
      event Kraken.UIKit.SignalDelegate SignalTitleBarUpdateLayout;
      event Kraken.UIKit.SignalDelegate SignalTitleBarIsVisible;
      event Kraken.UIKit.SignalDelegate SignalNavigationIsDisplaying;
      event Kraken.UIKit.SignalDelegate SignalWindowIsActivated;

      void SetTitleBarLayout(Windows.ApplicationModel.Core.CoreApplicationViewTitleBar value);
      void SetTitleBarVisibility(Windows.UI.Xaml.Visibility value);
      void SetNavigationView(Microsoft.UI.Xaml.Controls.NavigationView value);
      void SetWindowActivated(Single value); 
    };


    [default_interface]
    runtimeclass UIView : Windows.UI.Xaml.Controls.Page
    {
      UIView();
    };
  }
}
