macro(find_dependencies)
  # Add all external libs here.
  find_package(Git         REQUIRED)
  find_package(TBB         REQUIRED)
  find_package(Alembic     REQUIRED)
  find_package(Embree      REQUIRED)
  find_package(MaterialX   REQUIRED)
  find_package(OpenColorIO Required)
  find_package(OpenEXR     REQUIRED)
  find_package(OpenVDB     REQUIRED)
  find_package(OSL         REQUIRED)
  find_package(PTex        REQUIRED)
  find_package(PyOpenGL    REQUIRED)
  find_package(PySide      REQUIRED)
  find_package(Renderman   REQUIRED)
  find_package(TBB         REQUIRED)
  find_package(OpenGL      REQUIRED)
endmacro()
